name: schedule

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          $CONDA/bin/conda env update --file environment.yml --name base

      - name: Setup git config
        run: |
          git config --local user.email "jscnm1993+github_auto@gmail.com"
          git config --local user.name "Auto Commit"
          git remote set-url origin https://${{ github.actor }}:${{ secretes.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase

      - name: Run archive
        run: |
          python main.py

      - name: Checkout
        run: |
          git add .
          git commit -m "Auto commit from Github Action"
          git push
